version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ci_cd_DB__uri=postgresql://postgres:postgres@db:5432/ci_cd
      - ci_cd_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: ci_cd_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/ci_cd_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=ci_cd, ci_cd_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
